name: Create Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Build Assets
        uses: actions/upload-artifact@v2
        with:
          name: build-assets
          path: |
            build/*
            tekuCerts/*

      - name: Upload Release Assets
        uses: AButler/upload-release-assets@v2.0
        with:
          files: "./build/*,./tekuCerts/*"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref }}
